name: Hub
version: 0.0.1
author: mvcxznb
main: eu.hyperal.mvcxznb.Hub
description: Hub plugin
commands:
    hyperal:
        usage: /<command>
        description: HHub Command
    spawn:
        usage: /<command>
        description: Teleports player to the spawn